### PR TITLE
Adds stub documentation

### PR DESCRIPTION
**Pull request by palnabarun**

### CODE REVIEW

**Comment by anandology** [comment]
Why do we need so many files? Can't we start with just `index.rst` and add more files as needed? For firefly we have just one index.rst with all the docs.

**Comment by palnabarun** [comment]
Flask and requests maintain different files for different parts of their application.

**Comment by anandology** [comment]
I don't mind if you are ready to write that much documentation. :)

**Comment by palnabarun** [comment]
I am okay with both. Content will be same. :P

**Pull request merged**
